(+ (sum (var w)
        (* (var w)
           (rel E (var x) (var z) (var w))))
   (sum (var y)
        (* (sum (var w1)
                (* (var w1)
                   (rel R (var x) (var y) (var w1))))
           (sum (var w2)
                (* (var w2)
                   (rel E (var y) (var z) (var w2)))))))
