(sum (var w)
     (sum (var j)
          (* (* (var w) (* (I (<= 1 (var j)))
                           (I (<= (var j) (var t)))))
             (+ (* (I (= (var t) (var j)))
                   (rel v (var j) (var w)))
                (* (rel R (- (var t) 1) (var j) (var w))
                   (* (I (< (var j) (var t)))
                      (I (> (var t) 1))))))))
