(+ (* (I (> (var t) 1))
      (sum (var j)
           (sum (var w)
                (* (* (rel R (- (var t) 1) (var j) (var w))
                      (var w))
                   (* (I (<= (var j) (- (var t) 1)))
                      (I (<= 1 (var j))))))))
   (sum (var j)
        (sum (var w)
             (* (* (rel v (var j) (var w))
                   (var w))
                (* (I (= (var t) (var j)))
                   (I (<= 1 (var j))))))))
