(- (sum (var j)
        (sum (var w)
             (* (* (def R (var t) (var j) (var w))
                   (var w))
                (* (I (<= (var j) (var t)))
                   (I (>= (var j) 1))))))
   (sum (var j)
        (sum (var w)
             (* (* (def R (var t) (var j) (var w))
                   (var w))
                (* (I (>= (var j) 1))
                   (* (I (<= (var j)
                             (- (var t) (var k))))
                      (I (> (var t) (var k)))))))))
